# Makefile for ODZIP

CC      := gcc
CFLAGS  := -std=c17 -O2 -Wall -Wextra -pedantic -march=native -flto
LDFLAGS := -flto
TARGET  := odz
SRC     := main.c

.PHONY: all clean run

all: $(TARGET)

$(TARGET): $(SRC)
	$(CC) $(CFLAGS) -o $@ $^ $(LDFLAGS) compress.c decompress.c lz_hashchain.c odz_util.c

run: $(TARGET)
	./$(TARGET) c LICENSE output.odz
	./$(TARGET) d output.odz roundtrip
	cmp LICENSE roundtrip

clean:
	$(RM) $(TARGET) *.o output.odz roundtrip
