name: Release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-latest
            name: darwin-arm64
          - os: macos-13
            name: darwin-amd64
          - os: ubuntu-latest
            name: linux-amd64
          - os: windows-latest
            name: windows-amd64

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Configure
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DODZ_PORTABLE=ON

      - name: Build
        run: cmake --build build --config ${{ env.BUILD_TYPE }}

      - name: Test
        run: cmake --build build --target run

      - name: Package (unix)
        if: runner.os != 'Windows'
        run: |
          mkdir odz-${{ matrix.name }}
          cp build/odz odz-${{ matrix.name }}/
          cp LICENSE odz-${{ matrix.name }}/
          tar czf odz-${{ matrix.name }}.tar.gz odz-${{ matrix.name }}

      - name: Package (windows)
        if: runner.os == 'Windows'
        shell: bash
        run: |
          mkdir odz-${{ matrix.name }}
          cp build/${{ env.BUILD_TYPE }}/odz.exe odz-${{ matrix.name }}/
          cp LICENSE odz-${{ matrix.name }}/
          7z a odz-${{ matrix.name }}.zip odz-${{ matrix.name }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: odz-${{ matrix.name }}
          path: odz-${{ matrix.name }}.*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            odz-darwin-arm64.tar.gz
            odz-darwin-amd64.tar.gz
            odz-linux-amd64.tar.gz
            odz-windows-amd64.zip
